/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  CustomerProfileResponse,
  VerifyCustomerDto,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get profile
 */
export const customerPublicControllerProfile = () => {
  return customFetch<CustomerProfileResponse>({
    url: `/api/public/customer/profile`,
    method: 'GET',
  });
};

export const getCustomerPublicControllerProfileQueryKey = () => {
  return [`/api/public/customer/profile`] as const;
};

export const getCustomerPublicControllerProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof customerPublicControllerProfile>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof customerPublicControllerProfile>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCustomerPublicControllerProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof customerPublicControllerProfile>>
  > = () => customerPublicControllerProfile();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof customerPublicControllerProfile>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type CustomerPublicControllerProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof customerPublicControllerProfile>>
>;
export type CustomerPublicControllerProfileQueryError = ErrorType<unknown>;

export function useCustomerPublicControllerProfile<
  TData = Awaited<ReturnType<typeof customerPublicControllerProfile>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof customerPublicControllerProfile>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof customerPublicControllerProfile>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useCustomerPublicControllerProfile<
  TData = Awaited<ReturnType<typeof customerPublicControllerProfile>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof customerPublicControllerProfile>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof customerPublicControllerProfile>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useCustomerPublicControllerProfile<
  TData = Awaited<ReturnType<typeof customerPublicControllerProfile>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof customerPublicControllerProfile>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get profile
 */

export function useCustomerPublicControllerProfile<
  TData = Awaited<ReturnType<typeof customerPublicControllerProfile>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof customerPublicControllerProfile>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getCustomerPublicControllerProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Verify initData from telegram
 */
export const customerPublicControllerVerify = (
  verifyCustomerDto: VerifyCustomerDto,
) => {
  return customFetch<unknown>({
    url: `/api/public/customer/verify`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: verifyCustomerDto,
  });
};

export const getCustomerPublicControllerVerifyMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof customerPublicControllerVerify>>,
    TError,
    {data: VerifyCustomerDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof customerPublicControllerVerify>>,
  TError,
  {data: VerifyCustomerDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof customerPublicControllerVerify>>,
    {data: VerifyCustomerDto}
  > = props => {
    const {data} = props ?? {};

    return customerPublicControllerVerify(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type CustomerPublicControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof customerPublicControllerVerify>>
>;
export type CustomerPublicControllerVerifyMutationBody = VerifyCustomerDto;
export type CustomerPublicControllerVerifyMutationError = ErrorType<void>;

/**
 * @summary Verify initData from telegram
 */
export const useCustomerPublicControllerVerify = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof customerPublicControllerVerify>>,
    TError,
    {data: VerifyCustomerDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof customerPublicControllerVerify>>,
  TError,
  {data: VerifyCustomerDto},
  TContext
> => {
  const mutationOptions =
    getCustomerPublicControllerVerifyMutationOptions(options);

  return useMutation(mutationOptions);
};
