/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
export type MiniappsPublicControllerRecordsParams = {
  date?: string;
  serviceId?: string;
  specialistId?: string;
  mine?: string;
};

export type MiniappsPublicControllerStaffParams = {
  serviceId: string;
};

export type MiniappsPublicControllerServicesParams = {
  specialistId: string;
};

export interface MiniappCreateRecordDto {
  /** @nullable */
  client_email: string | null;
  client_name: string;
  client_phone: string;
  /** @nullable */
  comment: string | null;
  date: string;
  service_id: number;
  /** @nullable */
  specialist_id: number | null;
  time: string;
}

export type MiniappPublicBookingDtoStatus =
  (typeof MiniappPublicBookingDtoStatus)[keyof typeof MiniappPublicBookingDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MiniappPublicBookingDtoStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  canceled: 'canceled',
  completed: 'completed',
} as const;

export interface MiniappTimeslotDto {
  datetime: string;
  seance_length: number;
  time: string;
}

export interface MiniappPublicSpecialistDto {
  id: number;
  is_active: boolean;
  name: string;
  /** @nullable */
  photo_url: string | null;
  /** @nullable */
  role: string | null;
  /** @nullable */
  yclients_id: number | null;
}

/**
 * @nullable
 */
export type MiniappPublicBookingDtoSpecialist =
  MiniappPublicSpecialistDto | null;

export interface MiniappPublicServiceDto {
  /** @nullable */
  duration_sec: number | null;
  /** @nullable */
  duration_text: string | null;
  id: number;
  is_active: boolean;
  /** @nullable */
  price_max: number | null;
  /** @nullable */
  price_min: number | null;
  /** @nullable */
  price_text: string | null;
  /** @nullable */
  service_type: number | null;
  title: string;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  yclients_id: number | null;
}

export interface MiniappPublicBookingDto {
  date: string;
  id: number;
  service: MiniappPublicServiceDto;
  /** @nullable */
  specialist: MiniappPublicBookingDtoSpecialist;
  status: MiniappPublicBookingDtoStatus;
  time: string;
}

export interface MiniappPublicIntegrationDto {
  /** @nullable */
  address_text: string | null;
  city: string;
  /** @nullable */
  company_id: number | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  email: string | null;
  id: number;
  is_primary: boolean;
  /** @nullable */
  lat: number | null;
  /** @nullable */
  lng: number | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  telegram: string | null;
  /** @nullable */
  timezone: number | null;
  /** @nullable */
  timezone_name: string | null;
  /** @nullable */
  website: string | null;
  /** @nullable */
  whatsapp: string | null;
}

/**
 * @nullable
 */
export type MiniappPublicDtoIntegration = MiniappPublicIntegrationDto | null;

export interface MiniappPublicCompanyDto {
  id: number;
  title: string;
}

export interface MiniappPublicDto {
  companies: MiniappPublicCompanyDto[];
  /** @nullable */
  description: string | null;
  /** Miniapp identifier */
  id: number;
  /** @nullable */
  integration: MiniappPublicDtoIntegration;
  /** @nullable */
  logo_url: string | null;
  /** Miniapp name */
  name: string;
  photos: DBFile[];
  /** @nullable */
  public_title: string | null;
  reviews: MiniappPublicReviewDto[];
  /** @nullable */
  short_descr: string | null;
  /** Miniapp slug */
  slug: string;
  /** @nullable */
  title: string | null;
}

/**
 * @nullable
 */
export type MiniappPublicReviewDtoAuthorPhoto = DBFile | null;

export interface MiniappPublicReviewDto {
  /** Author */
  author: string;
  /** @nullable */
  author_photo: MiniappPublicReviewDtoAuthorPhoto;
  id: number;
  /** Rating */
  rating: number;
  /** Review text */
  text: string;
}

export interface VerifyCustomerDto {
  /** The initData from telegram */
  initData: string;
  /** Uniq code of referal */
  startParam?: string;
}

export interface CustomerProfileResponse {
  /** @nullable */
  first_name: string | null;
  /** ID from telegram */
  id: number;
  /** @nullable */
  last_name: string | null;
  /**
   * Phone of customer
   * @nullable
   */
  phone: string | null;
  /** @nullable */
  photo_url: string | null;
  /** @nullable */
  username: string | null;
}

export interface MiniappCompanyPreviewDto {
  /** @nullable */
  description: string | null;
  /** @nullable */
  logo_url: string | null;
  /** @nullable */
  public_title: string | null;
  /** @nullable */
  short_descr: string | null;
  /** @nullable */
  title: string | null;
}

export interface MiniappYclientsIntegrationPreviewDto {
  /** @nullable */
  address_text: string | null;
  city: string;
  /** @nullable */
  company_id: number | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  lat: number | null;
  /** @nullable */
  lng: number | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  telegram: string | null;
  /** @nullable */
  timezone: number | null;
  /** @nullable */
  timezone_name: string | null;
  /** @nullable */
  website: string | null;
  /** @nullable */
  whatsapp: string | null;
}

export interface MiniappYclientsPreviewDto {
  company: MiniappCompanyPreviewDto;
  integration: MiniappYclientsIntegrationPreviewDto;
}

export interface MiniappYclientsCreateDto {
  /** @nullable */
  company_id: number | null;
}

export interface MiniappUpdateDto {
  /** Miniapp name */
  name?: string;
  /** Miniapp slug */
  slug?: string;
  telegram_bot_token?: string;
}

export type MiniappBookingStatus =
  (typeof MiniappBookingStatus)[keyof typeof MiniappBookingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MiniappBookingStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  canceled: 'canceled',
  completed: 'completed',
} as const;

export interface MiniappBooking {
  date: string;
  id: number;
  status: MiniappBookingStatus;
  time: string;
}

/**
 * @nullable
 */
export type MiniappSpecialistPhoto = DBFile | null;

export interface MiniappSpecialist {
  id: number;
  is_active: boolean;
  name: string;
  /** @nullable */
  photo: MiniappSpecialistPhoto;
  /** @nullable */
  photo_url: string | null;
  /** @nullable */
  role: string | null;
  /** @nullable */
  yclients_id: number | null;
}

export interface MiniappService {
  /** @nullable */
  duration_sec: number | null;
  /** @nullable */
  duration_text: string | null;
  id: number;
  is_active: boolean;
  /** @nullable */
  price_max: number | null;
  /** @nullable */
  price_min: number | null;
  /** @nullable */
  price_text: string | null;
  /** @nullable */
  service_type: number | null;
  title: string;
  /** @nullable */
  weight: number | null;
  /** @nullable */
  yclients_id: number | null;
}

/**
 * @nullable
 */
export type MiniappReviewAuthorPhoto = DBFile | null;

export interface MiniappReview {
  /** Author */
  author: string;
  /** @nullable */
  author_photo: MiniappReviewAuthorPhoto;
  id: number;
  /** Rating */
  rating: number;
  /** Review text */
  text: string;
}

export interface MiniappYclientsIntegration {
  /** @nullable */
  address_text: string | null;
  city: string;
  /** @nullable */
  company_id: number | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  email: string | null;
  id: number;
  is_primary: boolean;
  /** @nullable */
  lat: number | null;
  /** @nullable */
  lng: number | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  telegram: string | null;
  /** @nullable */
  timezone: number | null;
  /** @nullable */
  timezone_name: string | null;
  /** @nullable */
  website: string | null;
  /** @nullable */
  whatsapp: string | null;
}

export interface MiniappDetailDto {
  bookings: MiniappBooking[];
  /** @nullable */
  description: string | null;
  id: number;
  /** @nullable */
  logo_url: string | null;
  name: string;
  photos: DBFile[];
  /** @nullable */
  public_title: string | null;
  reviews: MiniappReview[];
  services: MiniappService[];
  /** @nullable */
  short_descr: string | null;
  /** @nullable */
  slug: string | null;
  specialists: MiniappSpecialist[];
  /** @nullable */
  telegram_bot_token: string | null;
  /** @nullable */
  title: string | null;
  yclientsIntegrations: MiniappYclientsIntegration[];
}

export interface MiniappCreateDto {
  /** Miniapp name */
  name: string;
  /** Miniapp slug */
  slug: string;
  telegram_bot_token: string;
}

export interface MiniappListItemYclientsIntegrationDto {
  /** @nullable */
  address_text: string | null;
  /** @nullable */
  company_id: number | null;
}

export interface DBFile {
  /** Date when file was created */
  date_created: string;
  /** Date when file was updated */
  date_updated: string;
  /** Unique file identifier */
  id: number;
  /** Is file deleted */
  is_deleted: boolean;
  /** File mime type */
  mime_type: string;
  /** File url */
  url: string;
}

export interface MiniappListItemDto {
  id: number;
  integrations: MiniappListItemYclientsIntegrationDto[];
  name: string;
  photos: DBFile[];
  /** @nullable */
  slug: string | null;
}

export interface UpdateUserDto {
  /**
   * The email of the user
   * @nullable
   */
  email?: string | null;
  /** Is the user active? */
  is_active?: boolean;
  /** The login of the user */
  login?: string;
  /** The name of the user */
  name?: string;
  /** Users's password */
  password?: string;
}

export interface UserResponse {
  /** Date when the user was created */
  date_created: string;
  /** Date when the user was last active */
  date_last_active: string;
  /**
   * The email of the user
   * @nullable
   */
  email: string | null;
  /** Unique identifier for the user */
  id: number;
  /** Is the user active? */
  is_active: boolean;
  /** The login of the user */
  login: string;
  /** The name of the user */
  name: string;
}

export interface CreateUserDto {
  /**
   * The email of the user
   * @nullable
   */
  email: string | null;
  /** Is the user active? */
  is_active: boolean;
  /** The login of the user */
  login: string;
  /** The name of the user */
  name: string;
  /** Users's password */
  password: string;
}

export interface Manager {
  /** Date when the user was created */
  date_created: string;
  /** Date when the user was last active */
  date_last_active: string;
  /** Date when the user was last updated */
  date_updated: string;
  /**
   * The email of the user
   * @nullable
   */
  email: string | null;
  /** Unique identifier for the user */
  id: number;
  /** Is the user active? */
  is_active: boolean;
  /** The login of the user */
  login: string;
  /** The name of the user */
  name: string;
  /** Users's password */
  password: string;
}

export interface ManagerResponse {
  /** Date when the user was created */
  date_created: string;
  /** Date when the user was last active */
  date_last_active: string;
  /**
   * The email of the user
   * @nullable
   */
  email: string | null;
  /** Unique identifier for the user */
  id: number;
  /** Is the user active? */
  is_active: boolean;
  /** The login of the user */
  login: string;
  /** The name of the user */
  name: string;
}

export interface LoginUserDto {
  /** The login of the user */
  login: string;
  /** The password of the user */
  password: string;
}
