packages:
  - apps/*
  - packages/*

catalog:
  '@hookform/resolvers': ^5.2.0
  '@nestjs/cli': ^10.0.0
  '@nestjs/common': ^10.0.0
  '@nestjs/config': ^3.2.3
  '@nestjs/core': ^10.0.0
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.3
  '@nestjs/platform-express': ^10.0.0
  '@nestjs/schedule': ^6.0.0
  '@nestjs/schematics': ^10.0.0
  '@nestjs/serve-static': ^4.0.2
  '@nestjs/swagger': ^7.4.2
  '@nestjs/testing': ^10.0.0
  '@nestjs/throttler': ^6.4.0
  '@nestjs/typeorm': ^10.0.2
  '@radix-ui/react-checkbox': 1.3.2
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-scroll-area': 1.2.10
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tooltip': ^1.2.7
  '@tailwindcss/postcss': ^4.1.11
  '@types/express': ^4.17.17
  '@types/jest': ^29.5.2
  '@types/lodash': ^4.17.20
  '@types/multer': ^1.4.12
  '@types/node': ^20.3.1
  '@types/node-telegram-bot-api': ^0.64.7
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/supertest': ^6.0.0
  '@typescript-eslint/eslint-plugin': ^8.0.0
  '@typescript-eslint/parser': ^8.0.0
  bcryptjs: ^3
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cookie-parser: ^1.4.6
  date-fns: ^4.1.0
  dayjs: 1.11.13
  dotenv: ^16.4.5
  eslint: ^8.42.0
  eslint-config-prettier: ^9.0.0
  eslint-plugin-prettier: ^5.0.0
  file-type-mime: ^0.4.3
  jest: ^29.5.0
  jose: ^6.0.12
  lodash: 4.17.21
  lucide-react: 0.525.0
  multer: 1.4.5-lts.1
  nest-commander: 3.20.1
  next: 15.4.3
  node-telegram-bot-api: ^0.66.0
  openai: ^6.9.1
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  pg: ^8.13.0
  postcss: ^8.5.6
  prettier: ^3.0.0
  rate-limiter-flexible: ^7.2.0
  react-day-picker: ^9.8.1
  react-hook-form: 7.61.1
  react-toastify: ^11.0.5
  recharts: ^3.1.0
  reflect-metadata: ^0.2.0
  rxjs: ^7.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  tailwind-merge: 3.3.1
  tailwindcss: ^4.1.11
  telegram: ^2.26.22
  ts-jest: ^29.1.0
  ts-loader: ^9.4.3
  ts-node: ^10.9.1
  tsconfig-paths: ^4.2.0
  tw-animate-css: 1.4.0
  typeorm: ^0.3.25
  typescript: ^5.1.3
  zod: ^4.0.10

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - bufferutil
  - es5-ext
  - esbuild
  - utf-8-validate
  - ts-node
