/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsGet = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'GET',
  });
};

export const getWebhookPublicControllerYclientsGetQueryKey = () => {
  return [`/api/public/webhook/yclients`] as const;
};

export const getWebhookPublicControllerYclientsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWebhookPublicControllerYclientsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>
  > = () => webhookPublicControllerYclientsGet();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type WebhookPublicControllerYclientsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>
>;
export type WebhookPublicControllerYclientsGetQueryError = ErrorType<unknown>;

export function useWebhookPublicControllerYclientsGet<
  TData = Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWebhookPublicControllerYclientsGet<
  TData = Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWebhookPublicControllerYclientsGet<
  TData = Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Accept YClients webhook and save event
 */

export function useWebhookPublicControllerYclientsGet<
  TData = Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof webhookPublicControllerYclientsGet>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions =
    getWebhookPublicControllerYclientsGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsPost = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'POST',
  });
};

export const getWebhookPublicControllerYclientsPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>,
    void
  > = () => {
    return webhookPublicControllerYclientsPost();
  };

  return {mutationFn, ...mutationOptions};
};

export type WebhookPublicControllerYclientsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>
>;

export type WebhookPublicControllerYclientsPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept YClients webhook and save event
 */
export const useWebhookPublicControllerYclientsPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getWebhookPublicControllerYclientsPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsPut = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'PUT',
  });
};

export const getWebhookPublicControllerYclientsPutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>,
    void
  > = () => {
    return webhookPublicControllerYclientsPut();
  };

  return {mutationFn, ...mutationOptions};
};

export type WebhookPublicControllerYclientsPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>
>;

export type WebhookPublicControllerYclientsPutMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept YClients webhook and save event
 */
export const useWebhookPublicControllerYclientsPut = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPut>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getWebhookPublicControllerYclientsPutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsDelete = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'DELETE',
  });
};

export const getWebhookPublicControllerYclientsDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>,
    void
  > = () => {
    return webhookPublicControllerYclientsDelete();
  };

  return {mutationFn, ...mutationOptions};
};

export type WebhookPublicControllerYclientsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>
>;

export type WebhookPublicControllerYclientsDeleteMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept YClients webhook and save event
 */
export const useWebhookPublicControllerYclientsDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsDelete>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getWebhookPublicControllerYclientsDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsPatch = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'PATCH',
  });
};

export const getWebhookPublicControllerYclientsPatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>,
    void
  > = () => {
    return webhookPublicControllerYclientsPatch();
  };

  return {mutationFn, ...mutationOptions};
};

export type WebhookPublicControllerYclientsPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>
>;

export type WebhookPublicControllerYclientsPatchMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept YClients webhook and save event
 */
export const useWebhookPublicControllerYclientsPatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsPatch>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getWebhookPublicControllerYclientsPatchMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept YClients webhook and save event
 */
export const webhookPublicControllerYclientsHead = () => {
  return customFetch<void>({
    url: `/api/public/webhook/yclients`,
    method: 'HEAD',
  });
};

export const getWebhookPublicControllerYclientsHeadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>,
    void
  > = () => {
    return webhookPublicControllerYclientsHead();
  };

  return {mutationFn, ...mutationOptions};
};

export type WebhookPublicControllerYclientsHeadMutationResult = NonNullable<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>
>;

export type WebhookPublicControllerYclientsHeadMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept YClients webhook and save event
 */
export const useWebhookPublicControllerYclientsHead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof webhookPublicControllerYclientsHead>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getWebhookPublicControllerYclientsHeadMutationOptions(options);

  return useMutation(mutationOptions);
};
