/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookGet = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'GET',
  });
};

export const getSendpulsePublicControllerWebhookGetQueryKey = () => {
  return [`/api/public/sendpulse/webhook`] as const;
};

export const getSendpulsePublicControllerWebhookGetQueryOptions = <
  TData = Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSendpulsePublicControllerWebhookGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>
  > = () => sendpulsePublicControllerWebhookGet();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type SendpulsePublicControllerWebhookGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>
>;
export type SendpulsePublicControllerWebhookGetQueryError = ErrorType<unknown>;

export function useSendpulsePublicControllerWebhookGet<
  TData = Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useSendpulsePublicControllerWebhookGet<
  TData = Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useSendpulsePublicControllerWebhookGet<
  TData = Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */

export function useSendpulsePublicControllerWebhookGet<
  TData = Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sendpulsePublicControllerWebhookGet>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions =
    getSendpulsePublicControllerWebhookGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookPost = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'POST',
  });
};

export const getSendpulsePublicControllerWebhookPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>,
    void
  > = () => {
    return sendpulsePublicControllerWebhookPost();
  };

  return {mutationFn, ...mutationOptions};
};

export type SendpulsePublicControllerWebhookPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>
>;

export type SendpulsePublicControllerWebhookPostMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const useSendpulsePublicControllerWebhookPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSendpulsePublicControllerWebhookPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookPut = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'PUT',
  });
};

export const getSendpulsePublicControllerWebhookPutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>,
    void
  > = () => {
    return sendpulsePublicControllerWebhookPut();
  };

  return {mutationFn, ...mutationOptions};
};

export type SendpulsePublicControllerWebhookPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>
>;

export type SendpulsePublicControllerWebhookPutMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const useSendpulsePublicControllerWebhookPut = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPut>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSendpulsePublicControllerWebhookPutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookDelete = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'DELETE',
  });
};

export const getSendpulsePublicControllerWebhookDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>,
    void
  > = () => {
    return sendpulsePublicControllerWebhookDelete();
  };

  return {mutationFn, ...mutationOptions};
};

export type SendpulsePublicControllerWebhookDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>
>;

export type SendpulsePublicControllerWebhookDeleteMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const useSendpulsePublicControllerWebhookDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookDelete>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSendpulsePublicControllerWebhookDeleteMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookPatch = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'PATCH',
  });
};

export const getSendpulsePublicControllerWebhookPatchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>,
    void
  > = () => {
    return sendpulsePublicControllerWebhookPatch();
  };

  return {mutationFn, ...mutationOptions};
};

export type SendpulsePublicControllerWebhookPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>
>;

export type SendpulsePublicControllerWebhookPatchMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const useSendpulsePublicControllerWebhookPatch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookPatch>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSendpulsePublicControllerWebhookPatchMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const sendpulsePublicControllerWebhookHead = () => {
  return customFetch<void>({
    url: `/api/public/sendpulse/webhook`,
    method: 'HEAD',
  });
};

export const getSendpulsePublicControllerWebhookHeadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>,
    void
  > = () => {
    return sendpulsePublicControllerWebhookHead();
  };

  return {mutationFn, ...mutationOptions};
};

export type SendpulsePublicControllerWebhookHeadMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>
>;

export type SendpulsePublicControllerWebhookHeadMutationError =
  ErrorType<unknown>;

/**
 * @summary Accept Sendpulse webhook and save sendpulse_start payload
 */
export const useSendpulsePublicControllerWebhookHead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendpulsePublicControllerWebhookHead>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSendpulsePublicControllerWebhookHeadMutationOptions(options);

  return useMutation(mutationOptions);
};
