/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import type {AnalyticsEventDto} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Track miniapp analytics event
 */
export const analyticsPublicControllerTrack = (
  analyticsEventDto: AnalyticsEventDto,
) => {
  return customFetch<void>({
    url: `/api/public/analytics`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: analyticsEventDto,
  });
};

export const getAnalyticsPublicControllerTrackMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyticsPublicControllerTrack>>,
    TError,
    {data: AnalyticsEventDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof analyticsPublicControllerTrack>>,
  TError,
  {data: AnalyticsEventDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof analyticsPublicControllerTrack>>,
    {data: AnalyticsEventDto}
  > = props => {
    const {data} = props ?? {};

    return analyticsPublicControllerTrack(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type AnalyticsPublicControllerTrackMutationResult = NonNullable<
  Awaited<ReturnType<typeof analyticsPublicControllerTrack>>
>;
export type AnalyticsPublicControllerTrackMutationBody = AnalyticsEventDto;
export type AnalyticsPublicControllerTrackMutationError = ErrorType<unknown>;

/**
 * @summary Track miniapp analytics event
 */
export const useAnalyticsPublicControllerTrack = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyticsPublicControllerTrack>>,
    TError,
    {data: AnalyticsEventDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof analyticsPublicControllerTrack>>,
  TError,
  {data: AnalyticsEventDto},
  TContext
> => {
  const mutationOptions =
    getAnalyticsPublicControllerTrackMutationOptions(options);

  return useMutation(mutationOptions);
};
