/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  MiniappBooking,
  MiniappCreateRecordDto,
  MiniappPublicBookingDto,
  MiniappPublicDto,
  MiniappPublicServiceDto,
  MiniappPublicSpecialistDto,
  MiniappTimeslotDto,
  MiniappsPublicControllerRecordsParams,
  MiniappsPublicControllerServicesParams,
  MiniappsPublicControllerStaffParams,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Miniapp public detail
 */
export const miniappsPublicControllerBySlug = (
  slug: string,
  companyId: string,
) => {
  return customFetch<MiniappPublicDto>({
    url: `/api/public/miniapps/${slug}/${companyId}`,
    method: 'GET',
  });
};

export const getMiniappsPublicControllerBySlugQueryKey = (
  slug: string,
  companyId: string,
) => {
  return [`/api/public/miniapps/${slug}/${companyId}`] as const;
};

export const getMiniappsPublicControllerBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerBySlugQueryKey(slug, companyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>
  > = () => miniappsPublicControllerBySlug(slug, companyId);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>
>;
export type MiniappsPublicControllerBySlugQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerBySlug<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBySlug<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBySlug<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp public detail
 */

export function useMiniappsPublicControllerBySlug<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBySlug>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerBySlugQueryOptions(
    slug,
    companyId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Miniapp services
 */
export const miniappsPublicControllerServices = (
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
) => {
  return customFetch<MiniappPublicServiceDto[]>({
    url: `/api/public/miniapps/${slug}/${companyId}/services`,
    method: 'GET',
    params,
  });
};

export const getMiniappsPublicControllerServicesQueryKey = (
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
) => {
  return [
    `/api/public/miniapps/${slug}/${companyId}/services`,
    ...(params ? [params] : []),
  ] as const;
};

export const getMiniappsPublicControllerServicesQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerServicesQueryKey(slug, companyId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerServices>>
  > = () => miniappsPublicControllerServices(slug, companyId, params);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerServicesQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerServices>>
>;
export type MiniappsPublicControllerServicesQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerServices<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerServices<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerServices<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp services
 */

export function useMiniappsPublicControllerServices<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerServicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerServices>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerServicesQueryOptions(
    slug,
    companyId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Miniapp staff
 */
export const miniappsPublicControllerStaff = (
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
) => {
  return customFetch<MiniappPublicSpecialistDto[]>({
    url: `/api/public/miniapps/${slug}/${companyId}/staff`,
    method: 'GET',
    params,
  });
};

export const getMiniappsPublicControllerStaffQueryKey = (
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
) => {
  return [
    `/api/public/miniapps/${slug}/${companyId}/staff`,
    ...(params ? [params] : []),
  ] as const;
};

export const getMiniappsPublicControllerStaffQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerStaffQueryKey(slug, companyId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerStaff>>
  > = () => miniappsPublicControllerStaff(slug, companyId, params);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerStaffQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerStaff>>
>;
export type MiniappsPublicControllerStaffQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerStaff<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerStaff<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerStaff<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp staff
 */

export function useMiniappsPublicControllerStaff<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: MiniappsPublicControllerStaffParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerStaff>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerStaffQueryOptions(
    slug,
    companyId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Miniapp records
 */
export const miniappsPublicControllerRecords = (
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
) => {
  return customFetch<MiniappTimeslotDto[]>({
    url: `/api/public/miniapps/${slug}/${companyId}/records`,
    method: 'GET',
    params,
  });
};

export const getMiniappsPublicControllerRecordsQueryKey = (
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
) => {
  return [
    `/api/public/miniapps/${slug}/${companyId}/records`,
    ...(params ? [params] : []),
  ] as const;
};

export const getMiniappsPublicControllerRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerRecordsQueryKey(slug, companyId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerRecords>>
  > = () => miniappsPublicControllerRecords(slug, companyId, params);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerRecords>>
>;
export type MiniappsPublicControllerRecordsQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerRecords<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params: undefined | MiniappsPublicControllerRecordsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerRecords<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerRecords<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp records
 */

export function useMiniappsPublicControllerRecords<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  params?: MiniappsPublicControllerRecordsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerRecords>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerRecordsQueryOptions(
    slug,
    companyId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Miniapp bookings
 */
export const miniappsPublicControllerBookings = (
  slug: string,
  companyId: string,
) => {
  return customFetch<MiniappPublicBookingDto[]>({
    url: `/api/public/miniapps/${slug}/${companyId}/bookings`,
    method: 'GET',
  });
};

export const getMiniappsPublicControllerBookingsQueryKey = (
  slug: string,
  companyId: string,
) => {
  return [`/api/public/miniapps/${slug}/${companyId}/bookings`] as const;
};

export const getMiniappsPublicControllerBookingsQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerBookingsQueryKey(slug, companyId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerBookings>>
  > = () => miniappsPublicControllerBookings(slug, companyId);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerBookingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerBookings>>
>;
export type MiniappsPublicControllerBookingsQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerBookings<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBookings<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBookings<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp bookings
 */

export function useMiniappsPublicControllerBookings<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookings>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerBookingsQueryOptions(
    slug,
    companyId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create miniapp record
 */
export const miniappsPublicControllerCreateRecord = (
  slug: string,
  companyId: string,
  miniappCreateRecordDto: MiniappCreateRecordDto,
) => {
  return customFetch<MiniappBooking>({
    url: `/api/public/miniapps/${slug}/${companyId}/record`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: miniappCreateRecordDto,
  });
};

export const getMiniappsPublicControllerCreateRecordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>,
    TError,
    {slug: string; companyId: string; data: MiniappCreateRecordDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>,
  TError,
  {slug: string; companyId: string; data: MiniappCreateRecordDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>,
    {slug: string; companyId: string; data: MiniappCreateRecordDto}
  > = props => {
    const {slug, companyId, data} = props ?? {};

    return miniappsPublicControllerCreateRecord(slug, companyId, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsPublicControllerCreateRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>
>;
export type MiniappsPublicControllerCreateRecordMutationBody =
  MiniappCreateRecordDto;
export type MiniappsPublicControllerCreateRecordMutationError =
  ErrorType<unknown>;

/**
 * @summary Create miniapp record
 */
export const useMiniappsPublicControllerCreateRecord = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>,
    TError,
    {slug: string; companyId: string; data: MiniappCreateRecordDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsPublicControllerCreateRecord>>,
  TError,
  {slug: string; companyId: string; data: MiniappCreateRecordDto},
  TContext
> => {
  const mutationOptions =
    getMiniappsPublicControllerCreateRecordMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get miniapp booking
 */
export const miniappsPublicControllerBookingById = (
  slug: string,
  companyId: string,
  bookingId: string,
) => {
  return customFetch<MiniappPublicBookingDto>({
    url: `/api/public/miniapps/${slug}/${companyId}/booking/${bookingId}`,
    method: 'GET',
  });
};

export const getMiniappsPublicControllerBookingByIdQueryKey = (
  slug: string,
  companyId: string,
  bookingId: string,
) => {
  return [
    `/api/public/miniapps/${slug}/${companyId}/booking/${bookingId}`,
  ] as const;
};

export const getMiniappsPublicControllerBookingByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  bookingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsPublicControllerBookingByIdQueryKey(slug, companyId, bookingId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>
  > = () => miniappsPublicControllerBookingById(slug, companyId, bookingId);

  return {
    queryKey,
    queryFn,
    enabled: !!(slug && companyId && bookingId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsPublicControllerBookingByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>
>;
export type MiniappsPublicControllerBookingByIdQueryError = ErrorType<unknown>;

export function useMiniappsPublicControllerBookingById<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  bookingId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBookingById<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  bookingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsPublicControllerBookingById<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  bookingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get miniapp booking
 */

export function useMiniappsPublicControllerBookingById<
  TData = Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  companyId: string,
  bookingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsPublicControllerBookingById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsPublicControllerBookingByIdQueryOptions(
    slug,
    companyId,
    bookingId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
