/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  MiniappCreateDto,
  MiniappDetailDto,
  MiniappListItemDto,
  MiniappUpdateDto,
  MiniappYclientsCreateDto,
  MiniappYclientsPreviewDto,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Miniapps list
 */
export const miniappsAdminControllerList = () => {
  return customFetch<MiniappListItemDto[]>({
    url: `/api/admin/miniapps/list`,
    method: 'GET',
  });
};

export const getMiniappsAdminControllerListQueryKey = () => {
  return [`/api/admin/miniapps/list`] as const;
};

export const getMiniappsAdminControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof miniappsAdminControllerList>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMiniappsAdminControllerListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerList>>
  > = () => miniappsAdminControllerList();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerList>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsAdminControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsAdminControllerList>>
>;
export type MiniappsAdminControllerListQueryError = ErrorType<unknown>;

export function useMiniappsAdminControllerList<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof miniappsAdminControllerList>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerList>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerList<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof miniappsAdminControllerList>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerList>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerList<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof miniappsAdminControllerList>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapps list
 */

export function useMiniappsAdminControllerList<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof miniappsAdminControllerList>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsAdminControllerListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create miniapp
 */
export const miniappsAdminControllerCreate = (
  miniappCreateDto: MiniappCreateDto,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: miniappCreateDto,
  });
};

export const getMiniappsAdminControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerCreate>>,
    TError,
    {data: MiniappCreateDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerCreate>>,
  TError,
  {data: MiniappCreateDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerCreate>>,
    {data: MiniappCreateDto}
  > = props => {
    const {data} = props ?? {};

    return miniappsAdminControllerCreate(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof miniappsAdminControllerCreate>>
>;
export type MiniappsAdminControllerCreateMutationBody = MiniappCreateDto;
export type MiniappsAdminControllerCreateMutationError = ErrorType<unknown>;

/**
 * @summary Create miniapp
 */
export const useMiniappsAdminControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerCreate>>,
    TError,
    {data: MiniappCreateDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerCreate>>,
  TError,
  {data: MiniappCreateDto},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Miniapp detail
 */
export const miniappsAdminControllerById = (id: number) => {
  return customFetch<MiniappDetailDto>({
    url: `/api/admin/miniapps/${id}`,
    method: 'GET',
  });
};

export const getMiniappsAdminControllerByIdQueryKey = (id: number) => {
  return [`/api/admin/miniapps/${id}`] as const;
};

export const getMiniappsAdminControllerByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMiniappsAdminControllerByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerById>>
  > = () => miniappsAdminControllerById(id);

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerById>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsAdminControllerByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsAdminControllerById>>
>;
export type MiniappsAdminControllerByIdQueryError = ErrorType<unknown>;

export function useMiniappsAdminControllerById<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsAdminControllerById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerById<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsAdminControllerById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerById<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp detail
 */

export function useMiniappsAdminControllerById<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsAdminControllerByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update miniapp
 */
export const miniappsAdminControllerUpdate = (
  id: number,
  miniappUpdateDto: MiniappUpdateDto,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: miniappUpdateDto,
  });
};

export const getMiniappsAdminControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>,
    TError,
    {id: number; data: MiniappUpdateDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>,
  TError,
  {id: number; data: MiniappUpdateDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>,
    {id: number; data: MiniappUpdateDto}
  > = props => {
    const {id, data} = props ?? {};

    return miniappsAdminControllerUpdate(id, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>
>;
export type MiniappsAdminControllerUpdateMutationBody = MiniappUpdateDto;
export type MiniappsAdminControllerUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Update miniapp
 */
export const useMiniappsAdminControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>,
    TError,
    {id: number; data: MiniappUpdateDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerUpdate>>,
  TError,
  {id: number; data: MiniappUpdateDto},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Miniapp Yclients integrations
 */
export const miniappsAdminControllerListIntegrations = (id: number) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}/yclients`,
    method: 'GET',
  });
};

export const getMiniappsAdminControllerListIntegrationsQueryKey = (
  id: number,
) => {
  return [`/api/admin/miniapps/${id}/yclients`] as const;
};

export const getMiniappsAdminControllerListIntegrationsQueryOptions = <
  TData = Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getMiniappsAdminControllerListIntegrationsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>
  > = () => miniappsAdminControllerListIntegrations(id);

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type MiniappsAdminControllerListIntegrationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>
>;
export type MiniappsAdminControllerListIntegrationsQueryError =
  ErrorType<unknown>;

export function useMiniappsAdminControllerListIntegrations<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerListIntegrations<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useMiniappsAdminControllerListIntegrations<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Miniapp Yclients integrations
 */

export function useMiniappsAdminControllerListIntegrations<
  TData = Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof miniappsAdminControllerListIntegrations>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getMiniappsAdminControllerListIntegrationsQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create miniapp Yclients integration
 */
export const miniappsAdminControllerCreateIntegration = (
  id: number,
  miniappYclientsCreateDto: MiniappYclientsCreateDto,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}/yclients`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: miniappYclientsCreateDto,
  });
};

export const getMiniappsAdminControllerCreateIntegrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>,
    TError,
    {id: number; data: MiniappYclientsCreateDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>,
  TError,
  {id: number; data: MiniappYclientsCreateDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>,
    {id: number; data: MiniappYclientsCreateDto}
  > = props => {
    const {id, data} = props ?? {};

    return miniappsAdminControllerCreateIntegration(id, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerCreateIntegrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>
  >;
export type MiniappsAdminControllerCreateIntegrationMutationBody =
  MiniappYclientsCreateDto;
export type MiniappsAdminControllerCreateIntegrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Create miniapp Yclients integration
 */
export const useMiniappsAdminControllerCreateIntegration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>,
    TError,
    {id: number; data: MiniappYclientsCreateDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerCreateIntegration>>,
  TError,
  {id: number; data: MiniappYclientsCreateDto},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerCreateIntegrationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Preview miniapp Yclients integration
 */
export const miniappsAdminControllerPreviewIntegration = (
  id: number,
  miniappYclientsCreateDto: MiniappYclientsCreateDto,
) => {
  return customFetch<MiniappYclientsPreviewDto>({
    url: `/api/admin/miniapps/${id}/yclients-preview`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: miniappYclientsCreateDto,
  });
};

export const getMiniappsAdminControllerPreviewIntegrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>,
    TError,
    {id: number; data: MiniappYclientsCreateDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>,
  TError,
  {id: number; data: MiniappYclientsCreateDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>,
    {id: number; data: MiniappYclientsCreateDto}
  > = props => {
    const {id, data} = props ?? {};

    return miniappsAdminControllerPreviewIntegration(id, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerPreviewIntegrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>
  >;
export type MiniappsAdminControllerPreviewIntegrationMutationBody =
  MiniappYclientsCreateDto;
export type MiniappsAdminControllerPreviewIntegrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Preview miniapp Yclients integration
 */
export const useMiniappsAdminControllerPreviewIntegration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>,
    TError,
    {id: number; data: MiniappYclientsCreateDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerPreviewIntegration>>,
  TError,
  {id: number; data: MiniappYclientsCreateDto},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerPreviewIntegrationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete miniapp Yclients integration
 */
export const miniappsAdminControllerDeleteIntegration = (
  id: number,
  integrationId: number,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}/yclients/${integrationId}`,
    method: 'DELETE',
  });
};

export const getMiniappsAdminControllerDeleteIntegrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>,
    {id: number; integrationId: number}
  > = props => {
    const {id, integrationId} = props ?? {};

    return miniappsAdminControllerDeleteIntegration(id, integrationId);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerDeleteIntegrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>
  >;

export type MiniappsAdminControllerDeleteIntegrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Delete miniapp Yclients integration
 */
export const useMiniappsAdminControllerDeleteIntegration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerDeleteIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerDeleteIntegrationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Set miniapp primary Yclients integration
 */
export const miniappsAdminControllerSetPrimaryIntegration = (
  id: number,
  integrationId: number,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}/yclients/${integrationId}/primary`,
    method: 'PATCH',
  });
};

export const getMiniappsAdminControllerSetPrimaryIntegrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>,
    {id: number; integrationId: number}
  > = props => {
    const {id, integrationId} = props ?? {};

    return miniappsAdminControllerSetPrimaryIntegration(id, integrationId);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerSetPrimaryIntegrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>
  >;

export type MiniappsAdminControllerSetPrimaryIntegrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Set miniapp primary Yclients integration
 */
export const useMiniappsAdminControllerSetPrimaryIntegration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerSetPrimaryIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerSetPrimaryIntegrationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Refresh miniapp Yclients integration
 */
export const miniappsAdminControllerRefreshIntegration = (
  id: number,
  integrationId: number,
) => {
  return customFetch<void>({
    url: `/api/admin/miniapps/${id}/yclients/${integrationId}/refresh`,
    method: 'POST',
  });
};

export const getMiniappsAdminControllerRefreshIntegrationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>,
    {id: number; integrationId: number}
  > = props => {
    const {id, integrationId} = props ?? {};

    return miniappsAdminControllerRefreshIntegration(id, integrationId);
  };

  return {mutationFn, ...mutationOptions};
};

export type MiniappsAdminControllerRefreshIntegrationMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>
  >;

export type MiniappsAdminControllerRefreshIntegrationMutationError =
  ErrorType<unknown>;

/**
 * @summary Refresh miniapp Yclients integration
 */
export const useMiniappsAdminControllerRefreshIntegration = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>,
    TError,
    {id: number; integrationId: number},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof miniappsAdminControllerRefreshIntegration>>,
  TError,
  {id: number; integrationId: number},
  TContext
> => {
  const mutationOptions =
    getMiniappsAdminControllerRefreshIntegrationMutationOptions(options);

  return useMutation(mutationOptions);
};
