/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  CreateUserDto,
  Manager,
  UpdateUserDto,
  UserResponse,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get profile of authorized user
 */
export const managersAdminControllerMy = () => {
  return customFetch<Manager>({url: `/api/admin/managers/my`, method: 'GET'});
};

export const getManagersAdminControllerMyQueryKey = () => {
  return [`/api/admin/managers/my`] as const;
};

export const getManagersAdminControllerMyQueryOptions = <
  TData = Awaited<ReturnType<typeof managersAdminControllerMy>>,
  TError = ErrorType<Manager>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerMy>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getManagersAdminControllerMyQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof managersAdminControllerMy>>
  > = () => managersAdminControllerMy();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof managersAdminControllerMy>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type ManagersAdminControllerMyQueryResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerMy>>
>;
export type ManagersAdminControllerMyQueryError = ErrorType<Manager>;

export function useManagersAdminControllerMy<
  TData = Awaited<ReturnType<typeof managersAdminControllerMy>>,
  TError = ErrorType<Manager>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerMy>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof managersAdminControllerMy>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerMy<
  TData = Awaited<ReturnType<typeof managersAdminControllerMy>>,
  TError = ErrorType<Manager>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerMy>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof managersAdminControllerMy>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerMy<
  TData = Awaited<ReturnType<typeof managersAdminControllerMy>>,
  TError = ErrorType<Manager>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerMy>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get profile of authorized user
 */

export function useManagersAdminControllerMy<
  TData = Awaited<ReturnType<typeof managersAdminControllerMy>>,
  TError = ErrorType<Manager>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerMy>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getManagersAdminControllerMyQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new user
 */
export const managersAdminControllerCreate = (createUserDto: CreateUserDto) => {
  return customFetch<void>({
    url: `/api/admin/managers/list`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: createUserDto,
  });
};

export const getManagersAdminControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerCreate>>,
    TError,
    {data: CreateUserDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof managersAdminControllerCreate>>,
  TError,
  {data: CreateUserDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof managersAdminControllerCreate>>,
    {data: CreateUserDto}
  > = props => {
    const {data} = props ?? {};

    return managersAdminControllerCreate(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type ManagersAdminControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerCreate>>
>;
export type ManagersAdminControllerCreateMutationBody = CreateUserDto;
export type ManagersAdminControllerCreateMutationError = ErrorType<void>;

/**
 * @summary Create a new user
 */
export const useManagersAdminControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerCreate>>,
    TError,
    {data: CreateUserDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof managersAdminControllerCreate>>,
  TError,
  {data: CreateUserDto},
  TContext
> => {
  const mutationOptions =
    getManagersAdminControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Manager list
 */
export const managersAdminControllerList = () => {
  return customFetch<UserResponse[]>({
    url: `/api/admin/managers/list`,
    method: 'GET',
  });
};

export const getManagersAdminControllerListQueryKey = () => {
  return [`/api/admin/managers/list`] as const;
};

export const getManagersAdminControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof managersAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerList>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getManagersAdminControllerListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof managersAdminControllerList>>
  > = () => managersAdminControllerList();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof managersAdminControllerList>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type ManagersAdminControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerList>>
>;
export type ManagersAdminControllerListQueryError = ErrorType<unknown>;

export function useManagersAdminControllerList<
  TData = Awaited<ReturnType<typeof managersAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerList>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof managersAdminControllerList>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerList<
  TData = Awaited<ReturnType<typeof managersAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerList>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof managersAdminControllerList>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerList<
  TData = Awaited<ReturnType<typeof managersAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerList>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Manager list
 */

export function useManagersAdminControllerList<
  TData = Awaited<ReturnType<typeof managersAdminControllerList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof managersAdminControllerList>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getManagersAdminControllerListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user by id
 */
export const managersAdminControllerById = (id: number) => {
  return customFetch<UserResponse>({
    url: `/api/admin/managers/list/${id}`,
    method: 'GET',
  });
};

export const getManagersAdminControllerByIdQueryKey = (id: number) => {
  return [`/api/admin/managers/list/${id}`] as const;
};

export const getManagersAdminControllerByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof managersAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof managersAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getManagersAdminControllerByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof managersAdminControllerById>>
  > = () => managersAdminControllerById(id);

  return {queryKey, queryFn, enabled: !!id, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof managersAdminControllerById>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type ManagersAdminControllerByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerById>>
>;
export type ManagersAdminControllerByIdQueryError = ErrorType<unknown>;

export function useManagersAdminControllerById<
  TData = Awaited<ReturnType<typeof managersAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof managersAdminControllerById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof managersAdminControllerById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerById<
  TData = Awaited<ReturnType<typeof managersAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof managersAdminControllerById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof managersAdminControllerById>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useManagersAdminControllerById<
  TData = Awaited<ReturnType<typeof managersAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof managersAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get user by id
 */

export function useManagersAdminControllerById<
  TData = Awaited<ReturnType<typeof managersAdminControllerById>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof managersAdminControllerById>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getManagersAdminControllerByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update user by id
 */
export const managersAdminControllerUpdate = (
  id: number,
  updateUserDto: UpdateUserDto,
) => {
  return customFetch<UserResponse>({
    url: `/api/admin/managers/list/${id}`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: updateUserDto,
  });
};

export const getManagersAdminControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerUpdate>>,
    TError,
    {id: number; data: UpdateUserDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof managersAdminControllerUpdate>>,
  TError,
  {id: number; data: UpdateUserDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof managersAdminControllerUpdate>>,
    {id: number; data: UpdateUserDto}
  > = props => {
    const {id, data} = props ?? {};

    return managersAdminControllerUpdate(id, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type ManagersAdminControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerUpdate>>
>;
export type ManagersAdminControllerUpdateMutationBody = UpdateUserDto;
export type ManagersAdminControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary Update user by id
 */
export const useManagersAdminControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerUpdate>>,
    TError,
    {id: number; data: UpdateUserDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof managersAdminControllerUpdate>>,
  TError,
  {id: number; data: UpdateUserDto},
  TContext
> => {
  const mutationOptions =
    getManagersAdminControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete user by id
 */
export const managersAdminControllerRemove = (id: number) => {
  return customFetch<void>({
    url: `/api/admin/managers/list/${id}`,
    method: 'DELETE',
  });
};

export const getManagersAdminControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerRemove>>,
    TError,
    {id: number},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof managersAdminControllerRemove>>,
  TError,
  {id: number},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof managersAdminControllerRemove>>,
    {id: number}
  > = props => {
    const {id} = props ?? {};

    return managersAdminControllerRemove(id);
  };

  return {mutationFn, ...mutationOptions};
};

export type ManagersAdminControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof managersAdminControllerRemove>>
>;

export type ManagersAdminControllerRemoveMutationError = ErrorType<unknown>;

/**
 * @summary Delete user by id
 */
export const useManagersAdminControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof managersAdminControllerRemove>>,
    TError,
    {id: number},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof managersAdminControllerRemove>>,
  TError,
  {id: number},
  TContext
> => {
  const mutationOptions =
    getManagersAdminControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
