/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  DashboardAdminControllerListCountersParams,
  DashboardCountersResponse,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get ET Laser dashboard analytics
 */
export const dashboardAdminControllerListCounters = (
  params?: DashboardAdminControllerListCountersParams,
) => {
  return customFetch<DashboardCountersResponse>({
    url: `/api/admin/dashboard/dashboard`,
    method: 'GET',
    params,
  });
};

export const getDashboardAdminControllerListCountersQueryKey = (
  params?: DashboardAdminControllerListCountersParams,
) => {
  return [
    `/api/admin/dashboard/dashboard`,
    ...(params ? [params] : []),
  ] as const;
};

export const getDashboardAdminControllerListCountersQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
  TError = ErrorType<DashboardCountersResponse>,
>(
  params?: DashboardAdminControllerListCountersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getDashboardAdminControllerListCountersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>
  > = () => dashboardAdminControllerListCounters(params);

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type DashboardAdminControllerListCountersQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>
>;
export type DashboardAdminControllerListCountersQueryError =
  ErrorType<DashboardCountersResponse>;

export function useDashboardAdminControllerListCounters<
  TData = Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
  TError = ErrorType<DashboardCountersResponse>,
>(
  params: undefined | DashboardAdminControllerListCountersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useDashboardAdminControllerListCounters<
  TData = Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
  TError = ErrorType<DashboardCountersResponse>,
>(
  params?: DashboardAdminControllerListCountersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useDashboardAdminControllerListCounters<
  TData = Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
  TError = ErrorType<DashboardCountersResponse>,
>(
  params?: DashboardAdminControllerListCountersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get ET Laser dashboard analytics
 */

export function useDashboardAdminControllerListCounters<
  TData = Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
  TError = ErrorType<DashboardCountersResponse>,
>(
  params?: DashboardAdminControllerListCountersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dashboardAdminControllerListCounters>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getDashboardAdminControllerListCountersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
