/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  LoginUserDto,
  ManagerResponse,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Sign in for user
 */
export const adminAuthControllerLogin = (loginUserDto: LoginUserDto) => {
  return customFetch<ManagerResponse>({
    url: `/api/admin/auth/admin/auth/login`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: loginUserDto,
  });
};

export const getAdminAuthControllerLoginMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    TError,
    {data: LoginUserDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  {data: LoginUserDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    {data: LoginUserDto}
  > = props => {
    const {data} = props ?? {};

    return adminAuthControllerLogin(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type AdminAuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>
>;
export type AdminAuthControllerLoginMutationBody = LoginUserDto;
export type AdminAuthControllerLoginMutationError = ErrorType<void>;

/**
 * @summary Sign in for user
 */
export const useAdminAuthControllerLogin = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    TError,
    {data: LoginUserDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  {data: LoginUserDto},
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary User profile
 */
export const adminAuthControllerGetProfile = () => {
  return customFetch<ManagerResponse>({
    url: `/api/admin/auth/admin/getProfile`,
    method: 'GET',
  });
};

export const getAdminAuthControllerGetProfileQueryKey = () => {
  return [`/api/admin/auth/admin/getProfile`] as const;
};

export const getAdminAuthControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
      TError,
      TData
    >
  >;
}) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminAuthControllerGetProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminAuthControllerGetProfile>>
  > = () => adminAuthControllerGetProfile();

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type AdminAuthControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerGetProfile>>
>;
export type AdminAuthControllerGetProfileQueryError = ErrorType<void>;

export function useAdminAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
  TError = ErrorType<void>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useAdminAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
        TError,
        TData
      >,
      'initialData'
    >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useAdminAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary User profile
 */

export function useAdminAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof adminAuthControllerGetProfile>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getAdminAuthControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Sign out for user session
 */
export const adminAuthControllerLogout = () => {
  return customFetch<void>({
    url: `/api/admin/auth/admin/auth/logout`,
    method: 'POST',
  });
};

export const getAdminAuthControllerLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLogout>>,
    void
  > = () => {
    return adminAuthControllerLogout();
  };

  return {mutationFn, ...mutationOptions};
};

export type AdminAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>
>;

export type AdminAuthControllerLogoutMutationError = ErrorType<unknown>;

/**
 * @summary Sign out for user session
 */
export const useAdminAuthControllerLogout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions);
};
