/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  WalletBalanceResponseDto,
  WalletPublicControllerBalanceParams,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get customer loyalty balance
 */
export const walletPublicControllerBalance = (
  params: WalletPublicControllerBalanceParams,
) => {
  return customFetch<WalletBalanceResponseDto>({
    url: `/api/public/wallet/balance`,
    method: 'GET',
    params,
  });
};

export const getWalletPublicControllerBalanceQueryKey = (
  params: WalletPublicControllerBalanceParams,
) => {
  return [`/api/public/wallet/balance`, ...(params ? [params] : [])] as const;
};

export const getWalletPublicControllerBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWalletPublicControllerBalanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof walletPublicControllerBalance>>
  > = () => walletPublicControllerBalance(params);

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof walletPublicControllerBalance>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type WalletPublicControllerBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof walletPublicControllerBalance>>
>;
export type WalletPublicControllerBalanceQueryError = ErrorType<unknown>;

export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletPublicControllerBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletPublicControllerBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get customer loyalty balance
 */

export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getWalletPublicControllerBalanceQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
