/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * integrator project API
 * OpenAPI spec version: 1.0
 */
import {useMutation, useQuery} from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  WalletAmountDto,
  WalletBalanceResponseDto,
  WalletPublicControllerBalanceParams,
} from '../integratorProjectAPI.schemas';
import {customFetch} from '../../customFetch';
import type {ErrorType} from '../../customFetch';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get customer loyalty balance
 */
export const walletPublicControllerBalance = (
  params: WalletPublicControllerBalanceParams,
) => {
  return customFetch<WalletBalanceResponseDto>({
    url: `/api/public/wallet/balance`,
    method: 'GET',
    params,
  });
};

export const getWalletPublicControllerBalanceQueryKey = (
  params: WalletPublicControllerBalanceParams,
) => {
  return [`/api/public/wallet/balance`, ...(params ? [params] : [])] as const;
};

export const getWalletPublicControllerBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
) => {
  const {query: queryOptions} = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWalletPublicControllerBalanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof walletPublicControllerBalance>>
  > = () => walletPublicControllerBalance(params);

  return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
    Awaited<ReturnType<typeof walletPublicControllerBalance>>,
    TError,
    TData
  > & {queryKey: QueryKey};
};

export type WalletPublicControllerBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof walletPublicControllerBalance>>
>;
export type WalletPublicControllerBalanceQueryError = ErrorType<unknown>;

export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletPublicControllerBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): DefinedUseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof walletPublicControllerBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey};
/**
 * @summary Get customer loyalty balance
 */

export function useWalletPublicControllerBalance<
  TData = Awaited<ReturnType<typeof walletPublicControllerBalance>>,
  TError = ErrorType<unknown>,
>(
  params: WalletPublicControllerBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof walletPublicControllerBalance>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} {
  const queryOptions = getWalletPublicControllerBalanceQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Temporary method to top up loyalty balance
 */
export const walletPublicControllerTopup = (
  walletAmountDto: WalletAmountDto,
) => {
  return customFetch<WalletBalanceResponseDto>({
    url: `/api/public/wallet/topup`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: walletAmountDto,
  });
};

export const getWalletPublicControllerTopupMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletPublicControllerTopup>>,
    TError,
    {data: WalletAmountDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof walletPublicControllerTopup>>,
  TError,
  {data: WalletAmountDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof walletPublicControllerTopup>>,
    {data: WalletAmountDto}
  > = props => {
    const {data} = props ?? {};

    return walletPublicControllerTopup(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type WalletPublicControllerTopupMutationResult = NonNullable<
  Awaited<ReturnType<typeof walletPublicControllerTopup>>
>;
export type WalletPublicControllerTopupMutationBody = WalletAmountDto;
export type WalletPublicControllerTopupMutationError = ErrorType<unknown>;

/**
 * @summary Temporary method to top up loyalty balance
 */
export const useWalletPublicControllerTopup = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletPublicControllerTopup>>,
    TError,
    {data: WalletAmountDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof walletPublicControllerTopup>>,
  TError,
  {data: WalletAmountDto},
  TContext
> => {
  const mutationOptions =
    getWalletPublicControllerTopupMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Temporary method to spend loyalty balance
 */
export const walletPublicControllerSpend = (
  walletAmountDto: WalletAmountDto,
) => {
  return customFetch<WalletBalanceResponseDto>({
    url: `/api/public/wallet/spend`,
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    data: walletAmountDto,
  });
};

export const getWalletPublicControllerSpendMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletPublicControllerSpend>>,
    TError,
    {data: WalletAmountDto},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof walletPublicControllerSpend>>,
  TError,
  {data: WalletAmountDto},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof walletPublicControllerSpend>>,
    {data: WalletAmountDto}
  > = props => {
    const {data} = props ?? {};

    return walletPublicControllerSpend(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type WalletPublicControllerSpendMutationResult = NonNullable<
  Awaited<ReturnType<typeof walletPublicControllerSpend>>
>;
export type WalletPublicControllerSpendMutationBody = WalletAmountDto;
export type WalletPublicControllerSpendMutationError = ErrorType<unknown>;

/**
 * @summary Temporary method to spend loyalty balance
 */
export const useWalletPublicControllerSpend = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof walletPublicControllerSpend>>,
    TError,
    {data: WalletAmountDto},
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof walletPublicControllerSpend>>,
  TError,
  {data: WalletAmountDto},
  TContext
> => {
  const mutationOptions =
    getWalletPublicControllerSpendMutationOptions(options);

  return useMutation(mutationOptions);
};
